### ISSUE TITLE
HIT L0- Subcommutation of sector rates

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/imap_processing#1053]

**Comment by vmartinez-cu** [comment]
Need to handle subcommutation of sector rates (Use HIT_DERIVED tab in telemetry definition for how to deal with the subcommutation for each sectorrates fields).  [Diagram](https://lasp.colorado.edu/galaxy/display/IMAP/Sectored+Rates+Subcommutation)
