### ISSUE TITLE
Create MAG XTCE Packet Definition

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap_processing#108]
### Summary

Create XTCE packet definitions for use in MAG L1A algorithm using space packet parser. 

Currently blocked (mostly blocked) on getting complete packet definitions from MAG team. 

### Requirements

The more specific the better.
  - [ ] Create a MAG XTCE Packet definition

### Related tickets

#96

**Comment by greglucas** [comment]
I believe the MAG XTCE packet definitions are complete now in the combined XTCE file. Feel free to reopen or create a new ticket if you think there is more work to be done.
