### ISSUE TITLE
Ultra l2: Background reading for Nat

### ISSUE THREAD

**Issue by laspsandoval** [IMAP-Science-Operations-Center/imap_processing#1083]
### Requirements:

Read the powerpoint presentation and the Algorithm Document. 

https://lasp.colorado.edu/galaxy/display/IMAP/IMAP+Algorithm+Document+from+Instrument+Teams

https://lasp.colorado.edu/galaxy/display/IMAP/Ultra+Powerpoint+Slides?preview=/164269341/173704852/Ultra_algos_v3.pptx

**Comment by nkerman** [comment]
Read through both of these, and I have a decent understanding for now! I'm sure I'll want to return to these as I need to understand more specifics.
