### ISSUE TITLE
Ultra l2: Get Setup with MATLAB code for Nat

### ISSUE THREAD

**Issue by laspsandoval** [IMAP-Science-Operations-Center/imap_processing#1084]
### Algorithm Description:

Get MATLAB code running locally: https://lasp.colorado.edu/galaxy/x/HI3KCQ. I emailed you the same code using CU Large File Transfer System just in case you have a difficult time downloading it.

**Comment by nkerman** [comment]
Asked IT for access to files on lasp-store (large file transfer failing with lasp email account)

**Comment by nkerman** [comment]
Got it working on my machine! Still need to work through it to gain a more thorough understanding of the L2 parts of the code and how I'll go about implementing it, but setup is complete.
