### ISSUE TITLE
Document some CoDICE-specific SPICE examples

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#12]
It would be helpful to document some specific SPICE examples for CoDICE to use as reference while developing the pipeline.  We could try to build this _before_ the Science Team Meeting in August, but perhaps the SPICE training we take there will help us with this.

**Comment by GFMoraga** [comment]
CoDICE SPICE science:
   -  How does the CoDICE-Hi instrument's FOV change over a single spacecraft spin, and how are the spin-phase solid angles (Ω_(k,n)) calculated for each pixel k and spin phase n?
   -  What are the angular widths (α and β) of the pixels in the elevation and azimuth directions, and how do they impact the total solid angle observed by each Hi pixel during a spin?
- How are the directional intensities (I_j) for each Hi pixel and spin phase calculated based on the solid angles observed and the count rates (CR_j) measured at different energy steps?
- Can you explain the conversion process to obtain the CoDICE-Lo Intensities from the species rates (counts/seconds) using the energy geometric factor (GEm), efficiency (ε_ijl), and mass-to-charge ratio (E/q)?
- How are the directional and omnidirectional intensity distributions calculated, considering the spin phase (n) and sector (k) with appropriate mathematical conversion factors?
- What parameters are used to compute the symmetric moment for all species in the CoDICE-Hi instrument, and how are the 3D velocity distribution functions (VDFs) integrated to obtain these parameters?
