### ISSUE TITLE
Code for creating standard CDF files across instruments

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap_processing#125]
### Summary

We determined that we will use XArray to generate CDF files, so we need to create a standard piece of code which contains shared requirements from ISTP that instruments can use. 

### Requirements

The more specific the better.
  - [ ] Create a standardized way to create metadata which aligns with ISTP standards for CDF files
  - [ ] Create any common attributes, variables, or utility methods which would aid in CDF file writing

### Related tickets

Solves spike #71

**Comment by laspsandoval** [comment]
CDF?

**Comment by maxinelasp** [comment]
> CDF?

Thanks, let me update this 😆
