### ISSUE TITLE
Automatically deploy documentation to team site

### ISSUE THREAD

**Issue by greglucas** [IMAP-Science-Operations-Center/imap_processing#16]
We have an action set up to deploy the documentation to GitHub Pages currently, but it would be nice if we deployed to our actual website `imap-processing.com`, which will take a little extra effort like deciding where it should go, how we are serving static content, etc... This would be something good to look into in the future.

**Comment by maxinelasp** [comment]
@greglucas  is this complete with the readthedocs pages?

**Comment by greglucas** [comment]
Yeah, lets close this since we're using ReadTheDocs. If we do decide to deploy to our primary website we can create new tickets for that effort.
