### ISSUE TITLE
Add CI check for ruff warnings/errors

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#24]
We can configure our CI workflow to run `ruff` on our code and report any warnings/errors that come out of it.

**Comment by greglucas** [comment]
This is already done in the precommit.ci check (separate from GotHub Actions), so should be working I think for both ruff, black, and some other linting/housekeeping things.

**Comment by bourque** [comment]
Sorry I didn't catch that. Closing this issue as it is unnecessary.

**Comment by greglucas** [comment]
No problem! If you didn't catch it, I'm sure others won't either, so might be worth mentioning in your style guide where each of the checks is actually done on CI?
