### ISSUE TITLE
BUG - Github CI doc generation is not working with python 3.11

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/imap_processing#271]
## Description of the issue

When using python 3.11 in the CI doc.yml, sphinx does not pull from python's documentation. For example, a class with the super class `IntEnum` is causing an error in sphinx:

`/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/imap_processing/hit/l0/hit_l1a_decom.py:docstring of imap_processing.hit.l0.hit_l1a_decom.HitAPID:42:<autosummary>:1: WARNING: py:obj reference target not found: imap_processing.hit.l0.hit_l1a_decom.HitAPID.bit_count`

because it cannot find a target for built-in python functions in the Subclass 

This issue seems specific to the super class `IntEnum`. If using `Enum` instead the docs will build.

May be related to this issue:
https://github.com/sphinx-doc/sphinx/issues/10410

### Steps to reproduce the issue
1. 2. 3.

Run doc gen using commit #dd9464c

### Code Snippet:

```python
- name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
```

### Expected behavior (What should happen)

Docs should generate

### Actual behavior (What does happen)

`/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/imap_processing/hit/l0/hit_l1a_decom.py:docstring of imap_processing.hit.l0.hit_l1a_decom.HitAPID:42:<autosummary>:1: WARNING: py:obj reference target not found: imap_processing.hit.l0.hit_l1a_decom.HitAPID.bit_count`

**Comment by greglucas** [comment]
Possibly related? https://github.com/sphinx-doc/sphinx/issues/10410
