### ISSUE TITLE
Updates to Documentation based on feedback from February Meeting

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#335]
Some ideas on how to update our documentation based on feedback/conversation from the February Science Teams Meeting

- In the CDF docs, remove filename conventions section, instead link to existing naming conventions docs in style guide
- In the CDF docs, add and *example* of the global attributes that will be common across all files (we currently describe the contents in great detail, but don't provide a final example of what it looks like in a CDF file)
- Update README to include instructions on how to test L0-L1 processing code locally

**Comment by maxinelasp** [comment]
- In API docs, explain how to use imap-data-access for API access, or make it very clear that that is the recommended way to access the API in most cases
- In the CDF docs, link out to variable names defined by SPDF (for example, for quality flags)

**Comment by bourque** [comment]
#368 takes care of the first bullet

**Comment by bourque** [comment]
I've created separate issues for these, so I think this issue can be closed.
