### ISSUE TITLE
Setup Data processing repository

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/imap_processing#38]
**Summary**
A repository should be set up with automated workflows 

**Parent Requirement**
SOC-SDC-L4-62 | Configuration Management | The SDC shall maintain a version controlled Code Management Repository of the data processing software. | Requirement | Necessary to perform science processsing and analysis. | SOC-L3-91 | Inspection
-- | -- | -- | -- | -- | -- | --

**Tasks**
- [x] Create repository
- [x] #44 
- [x] Create automated workflows (GitHub actions)

**Comment by GFMoraga** [comment]
There is already a test.yml in the imap_processing/.github/workflows.
Is this new repo outside of imap_processing? 
If not, should I just be updating the  imap_processing/.github/workflows?

Trying to find a starting point. 
@sdhoyt

**Comment by GFMoraga** [comment]
I make a SPIKE to help explore this.

**Comment by greglucas** [comment]
The automated workflows were setup on the initial repository creation: https://github.com/IMAP-Science-Operations-Center/imap_processing/commit/40a266ab735e670f0ede013d0efaa97862f09fb5

Closing this as completed
