### ISSUE TITLE
Setup Versioning Process

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/imap_processing#39]
**Summary**
Define how we associated version of software to the data product and how software versions will work (ie. major and minor releases)

**Parent Requirement**
SOC-SDC-L4-62 | Configuration Management | The SDC shall maintain a version controlled Code Management Repository of the data processing software. | Requirement | Necessary to perform science processsing and analysis. | SOC-L3-91 | Inspection
-- | -- | -- | -- | -- | -- | --

**Tasks**
- [x] #43 
- [x] #48 
- [x] #49

**Comment by bourque** [comment]
I can take the lead on this one.
