### ISSUE TITLE
Document release procedure

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/imap_processing#40]
**Summary**
Document the procedure for software releases and how this will be handled for each instrument.

**Parent Requirement**
SOC-SDC-L4-63 | Software Management | The SDC shall provide tools and procedures for managing all software. | Requirement | All instrument team provided software will be managed at the SDC. | SOC-L3-91 | Inspection
-- | -- | -- | -- | -- | -- | --

**Tasks**
- #49

**Comment by bourque** [comment]
I can take the lead on this one.
