### ISSUE TITLE
SPIKE - Data Product Versioning

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#48]
## Description

This SPIKE is to discuss and determine the versioning scheme to be used for data products.  The IMAP SDC to Instrument Team ICD describes the [requirements](https://lasp.colorado.edu/galaxy/display/IMAP/IMAP+SDC+to+Instrument+Team+ICD#IMAPSDCtoInstrumentTeamICD-1.4FileNamingConventions) for this as follows:

```
Format: vNN-NN
The initial value is “v01-00”. Values of “v00-NN” may be used for beta versions prior to deployment at the SDC.
ITs are allowed flexibility in determining what constitutes a major or minor version change, as long as the reason
for the change is documented.
```

## Requirements
- The scheme must be of the format `vXX-YY`, where `XX` is the "major" version and `YY` is the "minor" version
- The version of the initial deployment of data products must be `v01-00`.
- Beta versions prior to deployment may be `v00-NN`

## Additional notes
- The IMAP SDC dev team is considered the "ITs" in the requirement, meaning that we can decide "what constitutes a major and minor version change"

## Related tickets
- #39 

# Summary
TBD

**Comment by bourque** [comment]
It seems to me that there are several small variations of a solution here, so I will only briefly describe them below.  From what I've heard, these four solutions more-or-less follow the scheme that other missions use, so these would be consistent with other missions.  There are probably more solutions we could explore if we want to deviate from this, but I will leave that open for discussion here.

## Solution 1

- Major version number is updated when any change to the algorithm is made
- Minor version number is updated when data are reprocessed with the same algorithm, but perhaps with different ancillary files/calibrations (e.g. SPICE kernels)
- Minor version number is reset to 0 when the major version number is updated
- The version is not specific to an instrument's algorithm.  For example, the version will be updated for all IMAP products even if just one instrument's algorithm has been updated.

## Solution 2

Same as solution 1, except the version is specific to an instrument.  In other words, each instrument will keep track of their own version number and will independently be updated based on that instrument's algorithm development.

## Solution 3

Same as solution 1, but the minor version number is never reset to 0

## Solution 4

Same as solution 1, but the minor version is never reset to 0, and versions are specific to an instrument.

**Comment by greglucas** [comment]
A few somewhat related things to consider:
1. Can these be different between instruments? i.e. MAG_05, but Hi_03 would be produced at the same time because the instruments have updated their algorithms at different times and MAG has made more updates. That might get confusing across the mission to know that a MAG_05 data product was used as input to Hi_03. But at the same time, MAG might not want to increment their data product version if they didn't make updates but we needed to for a different instrument.
2. Would a full mission reprocessing bring everyone onto the same version number?
3. If we bump the algorithm version do we automatically reset the minor version down to 00 and restart that? Or do these two numbers increment independently?

**Comment by bourque** [comment]
@greglucas @tech3371 @laspsandoval @sdhoyt @maxinelasp @bryan-harter @GFMoraga

If you have any other ideas or opinions on how we should version our data products, please share your thoughts here.  Thank you!

**Comment by bryan-harter** [comment]
So I think the biggest things to make sure are 

1. It is super obvious which file is the latest and greatest 
2. Each file has a record of the files that were used as input to create it
3. We never overwrite/delete those old files

So I *think* all of these solutions work with the above points, and it's really just an issue of what would be easier for us and what makes the most sense to the project scientists.  This might be a question we ask everyone in a few weeks to see if there are strong feelings one way or another.  

But I'll chime in with my preference, which is Solution 2.  That's mainly for issues I see with mission-wide versioning when it comes to reprocessing:

1. When an instrument's algorithm is updated, it's pretty common to do a full mission reprocess for that instrument.  For example, if we made a giant change to the IMAP-Lo/High/Ultra algorithms and decided it was worth updating the repository to version 5, we'd need to reprocess all instrument data and move them up to a version 5 to be consistent, even though perhaps nothing has changed with the other instrument's algorithms.
2. To expand on the above point, there will probably be some instruments with algorithms that we barely touch again after next year.  For instance, the MAVEN MAG instrument has only tweaked their algorithm one time in 9 years (and it was so minor they decided to only go from v01-01 to v01-02).  With project-wide versioning, my worry is that in 2030 someone would come along and see IMAP MAG files are now v35 and think papers written using v01 data are out of date, when in reality the files are identical. 
3. If we skirt around the issues above by not reprocessing files without an algorithm update, then we're dealing with different file versions of different instruments on the SDC anyway

**Comment by maxinelasp** [comment]
I would rather have the instruments only reprocess when needed, but keep the version of the code in the file name (related to your 3). This way, it would be easy to go back and see the state of the entire code base when the file was processed. It does mean different instruments will have different versions associated with them, but it would make the link between data file versions and code versions really clear, which is appealing to me. 

But, I also see what you're saying about it being unclear if the algorithm changed. I didn't consider that people might be worried they were using outdated info. That's more convincing to me that we do need instrument-specific versioning.

**Comment by tech3371** [comment]
I think solution 2 is good.

If we go down solution 2, a question regarding mission wide reprocessing, will every instrument use their latest and greatest version to reprocess? and their filename will reflect version it was used which could be different for each instrument but should match with their latest version?

**Comment by bourque** [comment]
Thank you all for your comments!

Just so I can get this all documented in time for SIT2, we will move ahead with solution 2 for now.  We can revisit this down the road if we are finding that it is not working for us.
