### ISSUE TITLE
Document software and data product versioning schemes in Style Guide

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#49]
### Description:

The versioning schemes that we decide on in #43 and #48 should be documented in the style guide.

### Related:

- #43 
- #48
- #39 
- #54 
- #55

**Comment by maxinelasp** [comment]
Can I suggest a new document about versioning which is linked from the style guide? It seems likely we will have a fair amount to say on the topic with the file version numbers.
