### ISSUE TITLE
Create HIT L1A CDF for Count Rates

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/imap_processing#514]
### Summary

The HIT Count Rates L1A science data product data must be put into a xarray dataset and written to a CDF. This work will including setting all the the necessary CDF attributes as well.

**Comment by vmartinez-cu** [comment]
- [ ] Write L1A Count Rates Data Class
- [ ] Create Count Rates CDF Attributes Diagram and Review with Instrument Team
- [ ] Create Count Rates CDF Attributes YAML
- [ ] Create Count Rates Dataset
