### ISSUE TITLE
[L5] Produce L1A CDF formatted data products for CoDICE

### ISSUE THREAD

**Issue by GFMoraga** [IMAP-Science-Operations-Center/imap_processing#64]
### Summary of the L5 requirement

The SDC needs to produce L1A CDF formatted data products for the MAG instrument. The data products for L1A can be found in the MAG algorithm document here: https://lasp.colorado.edu/galaxy/display/IMAP/IMAP+Algorithm+Document+from+Instrument+Teams

### Parent requirement

SOC-SDC-L4-29 | SDC Execution of L1 Processing Software | The SDC shall be capable of executing L1 processing software to produce L1 data products within seven (7) days of receipt of all requisite data inputs. | Requirement | The SDC produces L1 data products via Instrument Team supplied algorithms and SDC produced processing code. | SOC-L3-57 | Test | SIT-3: L0 -> L1 processing | SIT-3
-- | -- | -- | -- | -- | -- | -- | -- | --

### Tasks

- [x] #6 
- [x] #247
- [x] #176 
- [x] #248
- [x] #249
- [x] #252
- [x] #251

**Comment by maxinelasp** [comment]
Blocked on #71

**Comment by bourque** [comment]
This is now being kept track in #252
