### ISSUE TITLE
Updates to IDEX L1 code for consistency

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#656]
There are a few updates we can make to the IDEX L1 code to be more consistent with other instruments' pipelines:

- Generate an updated packet definition file with recent version of `space_packet_parser`
- Separate out the L0 decommutation code and the L1 processing code within `idex_packet_parser.py`, and update unit tests accordingly
- Switch CDF attribute definitions to use yaml files instead of dataclasses
- ~Add call to `write_cdf()` within pipeline so that CDFs get created _within_ the pipeline, instead of within `cli.py`~

**Comment by tmplummer** [comment]
You may want to hold off on that final bullet. I think that @greglucas had some compelling reasons as to why the pipelines should not be calling `write_cdf()`.
