### ISSUE TITLE
SPICE - Update met_to_j2000ns

### ISSUE THREAD

**Issue by laspsandoval** [IMAP-Science-Operations-Center/imap_processing#689]
### Summary

Update /Users/lasa6858/imap_processing/imap_processing/cdf/utils/met_to_j2000ns so that it is more accurate by using the spacecraft clock kernel.

MET - spacecraft ticks (close to a second)
SCLK - shows how to adjust clock ticks to a true time

kernel location: https://lasp.colorado.edu/galaxy/display/IMAP/Data

You will need to 
1. furnish the sclk ([imap_sclk_0000.tsc](https://lasp.colorado.edu/galaxy/download/attachments/173719425/imap_sclk_0000.tsc?version=1&modificationDate=1711400549607&api=v2)) and leapsecond ([naif0012.tls](https://lasp.colorado.edu/galaxy/download/attachments/173719425/naif0012.tls?version=1&modificationDate=1711400551089&api=v2)) kernels similar to how it works in spice_examples.py:
with spice.KernelPool(kernels): etc.
2. Use relevant tool/tools listed here to update the met: https://spiceypy.readthedocs.io/en/main/documentation.html#spiceypy.spiceypy

### Requirements

The more specific the better.
  - Implement SPICE SCLK in met_to_j2000ns

**Comment by tmplummer** [comment]
For this ticket I suggest that the function should ignore the need to furnish the kernels. Assume that the needed kernels will already be furnished. That piece will eventually be taken care of by the decorator that I will implement. For testing, you will need to furnish the kernels noted in the ticket description in the test function before calling `met_to_j2000ns`.

**Comment by tmplummer** [comment]
I would also suggest that `met_to_j2000ns` be a wrapper around a function called `met_to_j2000` which returns double precision floating point seconds since J2000. That function in turn should essentially vectorize the underlying spiceypy function that does the conversion.

**Comment by vmartinez-cu** [comment]
I still have some reading up to do on SPICE. What is meant by "furnish" kernels?

**Comment by tmplummer** [comment]
> What is meant by "furnish" kernels?

When you furnish a kernel, by calling `spiceypy.furnish()`, you are really just "loading the kernel into the program". This lets SPICE know about the kernel. It opens the kernel and reads some metadata to understand what information the kernel provides. That is really all furnishing does.

This page has a nice overview of kernels: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/info/intrdctn.html

**Comment by tmplummer** [comment]
One piece of background info that I thought might not be obvious is that SPICE source code is written in FORTRAN. NASA's Navigation and Ancillary Information Facility (NAIF) created a C wrapper for the FORTRAN code and provides compiled shared objects that can be called from C. The `spiceypy` package essentially just wraps the C code such that it can be called from python. If you look at the `spiceypy` documentation, all of the function documentation link directly to the NAIF CSPICE documentation.
