### ISSUE TITLE
Update CoDICE Galaxy page 

### ISSUE THREAD

**Issue by GFMoraga** [IMAP-Science-Operations-Center/imap_processing#7]
Topic: CoDICE galaxy page
Description: Unpack and add information to the Galaxy page.
[https://lasp.colorado.edu/galaxy/display/IMAP/CoDICE](url)

Follow-up comments:
Focus on L1A and L1B

**Comment by GFMoraga** [comment]
Updated page with algorithm document updates. Algorithm, command, and telemetry packets where updated on 6/29/23

**Comment by bourque** [comment]
We will update the CoDICE area on Galaxy as new info comes in. Interested parties are encouraged to check the page history on galaxy to see what has been updated. Otherwise, we are closing this issue.
