### ISSUE TITLE
Create CDF style guide in documentation

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap_processing#70]
### Overview

Following the example CDF style guide for MMS, create a CDF style guide for IMAP. 

Should include:
- SPDF required fields
- Any expected values which you can know ahead of time (PI list, etc)
- variable name requirements
- Specifications for ordering, etc

This style guide is expected to be basically a copy of the MMS style guide, but with any IMAP specific information updated. It will act as a reference for other CDK files from us or external teams. 

### Related documents or information sources

The file can be found here: https://lasp.colorado.edu/galaxy/display/mms/DSWG?preview=/5702460/27656210/MMS_CDF_Format_GuideV1.8.pdf 

or, email Bryan Harter or Kris Larsen for access.

**Comment by bourque** [comment]
@bryan-harter has created this here! https://imap-processing--273.org.readthedocs.build/en/273/development/cdf_guide.html
