### ISSUE TITLE
Fix MAG CDF attrs

### ISSUE THREAD

**Issue by tech3371** [IMAP-Science-Operations-Center/imap_processing#715]
Finish remaining CDF attrs updates from this PR: https://github.com/IMAP-Science-Operations-Center/imap_processing/pull/714

- imap_processing/mag/l0/decom_mag.py
- imap_processing/cdf/config/imap_mag_l1_variable_attrs.yaml
- imap_processing/tests/mag/test_mag_decom.py

**Comment by maxinelasp** [comment]
Solved in PR #693
