### ISSUE TITLE
SPIKE - Good times/bad times API

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap_processing#73]
## Description

Create a description of a good times/bad times api, and determine if that's something useful to any of the instrument teams. 

## Requirements
- Create a basic API design
- Document each team's answer to "Is this useful"

### Nice to have or Goal Requirements
- None

## Additional notes
This API might look like sending a request with a time in, and getting a response for the time out. This may be related to the "good times/bad times" universal table for Lo, High, Ultra. Each instrument has unique good times/bad times. 

## Follow up tickets
This spike is not considered complete until at least one follow up issue is created. 
- [ ] Placeholder ticket

**Below is the template for the response to this ticket. Add as many solutions as needed, but preferably include 2-5 for discussion. The response should be posted as a comment on this issue, or linked in a comment. **

# Solution 1
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Solution 2
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Summary
Write up a summary of your findings, including your preferred solution.

**Comment by sdhoyt** [comment]
After discussions with instrument teams, it's been determined that a Good times/bad times API is not needed, but would be a "nice to have" feature. This API may be added in the future, but is not necessary to discuss at this time. Closing this SPIKE with that result.
