### ISSUE TITLE
Xtce build follow up: make updates on closed PR #72

### ISSUE THREAD

**Issue by GFMoraga** [IMAP-Science-Operations-Center/imap_processing#75]
### Summary
This is a way to track the progress of updating the xtce files and parsing tools 

### Completed
- [x] We need to add pandas, openpyxl to poetry dependency list: **added to dependencies, and not optional dependencies.** 
- [x] Made a new directory called 'tools' under the 'imap_processing', as well as 'tools/xtce_generation' which will house the files to make xtce
- [x] Fix linting issues
- [x] Moving docstrings around to be compliant with PEP257/numpydocs
- [x] Adding said documentation to the imap_processing docs (as well as any other outward-facing docs we want to add)
- [x] Utilizing** classes, config files, or argument parsing to abstract out parameters from the code
- [x] Make the code more generalized, generally speaking
- [x] Squash merge commits
- [x] Create for loop for each row in lengthInBits column and use that to create IntegerParameterType. That way, if there are int sizes greater than 32 or unique values after that, they would get created.
- [x] Fix Matthew's code suggestion on the ".org/space/xtce"

### Requirements

The more specific the better.
  - Review closed PR #72 
  

### Related tickets

#72

**Comment by GFMoraga** [comment]
@bourque I copied your comment from the PR as a starter. I will go back and edit/update.

**Comment by bourque** [comment]
Thanks @GFMoraga. I am also happy to help out with some of this!

**Comment by GFMoraga** [comment]
@maxinelasp can you suggest names for classes? Or do you think these are fine? I am working on this comment:

"It is best practice to have the main function be really small and call out to other methods (IMO). Ideally, this would look something like:"

df = parse_excel_file(filename)
header = generate_header()
integer_parameter_types = generate_integer_parameter_types()
codice_parameters = generate_codice_parameters()
tree = generate_xml_tree(df, header, integer_parameter_types, codice_parameters)
tree.write(...)

**Comment by GFMoraga** [comment]
@tech3371 how do I do this? "We need to add pandas, openpyxl to poetry dependency list" in poety.toml?

**Comment by maxinelasp** [comment]
Make sure your names are clear, with spelled out names (per the [style guide](https://imap-processing.readthedocs.io/en/latest/development/style_guide/python-coding.html)). Ideally, it should be clear what the class is without other developers needing to read any documentation or comments. If you're having trouble describing a class in 2-3 words, that is a sign the class is too complicated and may need to be split down further. 

Here's an [interesting discussion](https://stackoverflow.com/questions/38019/whats-the-best-approach-to-naming-classes) that might help. Naming things is difficult and annoying 😆

**Comment by maxinelasp** [comment]
You can also look at `space_packet_parser` for [examples](https://github.com/medley56/space_packet_parser/blob/master/space_packet_parser/parser.py) of class names/structure.

**Comment by maxinelasp** [comment]
Also, per your poetry question, I will write up a document about using poetry which we can use as a start.

**Comment by GFMoraga** [comment]
Sounds good! I will take a look, and yes, naming things, I am learning is harder than I thought!

**Comment by tech3371** [comment]
@GFMoraga I found this book very helpful. I read first few chapters. Chapter 2 talks about how to name functions well. I hope it helps.
https://github.com/jnguyen095/clean-code/blob/master/Clean.Code.A.Handbook.of.Agile.Software.Craftsmanship.pdf
