### ISSUE TITLE
Add tests for XTCE packet parsing

### ISSUE THREAD

**Issue by greglucas** [IMAP-Science-Operations-Center/imap_processing#784]
### Summary

There are currently no tests for the XTCE converter content. We should add some tests that mock up a spreadsheet and convert it to an XTCE file with the expected content.

Similar to the `metadata_generation` tools where we are mocking up spreadsheet tabs already: https://github.com/IMAP-Science-Operations-Center/imap_processing/blob/dev/tools/metadata_generation/tests/test_metadata_generation.py

### Requirements

The more specific the better.
  - [ ] Mock up a spreadsheet with a few packets and tabs (don't add an Excel sheet to the repo)
  - [ ] Get full coverage for the XTCE converter class

**Comment by bourque** [comment]
I think this could be a good student task, so I marked it as such

**Comment by greglucas** [comment]
Apparently we already had this in the test suite, so I'm going to close this issue as already completed. Sorry for the indirection here! See: https://github.com/IMAP-Science-Operations-Center/imap_processing/pull/783 for a discussion of the updates to dynamically generate the file instead of using the manually saved version.
