### ISSUE TITLE
codecov check should not include conftest.py

### ISSUE THREAD

**Issue by tmplummer** [IMAP-Science-Operations-Center/imap_processing#845]
### Algorithm Description:
~~Our code coverage metrics shouldn't care about test directories.~~
After discussion in a team tag-up, the approach we decided on was to ignore all `conftest.py` files from test coverage. It can be useful to have test coverage metrics on test files.

**Comment by greglucas** [comment]
I disagree with this. I believe that we want all tests to be run and know if tests are not being run. If codecov doesn't see a test being run, that means the test is pointless. We should have at least one runner to run every test if we can and get full coverage in the tests/ folder.

I think others have this same thought as you though, so I may be the only one who cares about test coverage 🤷 and we should actually do this.

**Comment by tmplummer** [comment]
> I disagree with this. I believe that we want all tests to be run and know if tests are not being run. If codecov doesn't see a test being run, that means the test is pointless. We should have at least one runner to run every test if we can and get full coverage in the tests/ folder.

Thanks, @greglucas. I hadn't considered that the coverage can actually diagnose issues with how tests have been implemented. After reading a quick blurb on codecov, I agree with you.

**Comment by greglucas** [comment]
Consensus on the call was to ignore `conftest.py` fixture files, but leave the test coverage in tact.
