### ISSUE TITLE
Validate HIT L1A Pulse Height Event

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/imap_processing#959]
PHA data can't be validated against the provided validation file since the SDC will not be decommutating this data. Menlo will be handling this process. Also, variable attributes won't be needed since the CDF will only contain one data variable for the binary PHA data. Validation for PHA will consist of verifying with HIT that the limited metadata is complete.

**Comment by vmartinez-cu** [comment]
HIT confirmed that validation will look different for PHA and may need to be handled by Menlo. Closing ticket
